using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Higher_Lower
{
    class Program
    {
        static void Main(string[] args)
        {
            //A random number is generated here for the user to guess.
            //This number should not be shown to the user.
            int RandomNumber = new Random().Next(100);

            //Here an introduction to the game is given. $@ is for multiple lines.
            var WelcomeText =
$@"Welcome to the game higer or lower!
Press any button to continue.";
            Console.WriteLine(WelcomeText);
            Console.ReadKey(true);

            //Introduction resumed.
            var SecondWelcome =
$@"The objective of this game is to guess the number between 0 and 100 generated by this application.
If you guess incorrectly, the game will tell you whether the number you are looking for is higher or lower.
Good luck!
Press any button to continue.";
            Console.WriteLine(SecondWelcome);
            Console.ReadKey(true);

          

            {
                Console.WriteLine("Guess a number between the 0 and 100");



                    string input = Console.ReadLine();
                int userentry = Convert.ToInt32(input);
                string Gok = Console.ReadLine();
                int Invul = Convert.ToInt32(Gok);
                while (Invul != RandomNumber)

                    if (userentry > RandomNumber)
                {
                    Console.WriteLine($"You entered {userentry}. That's too  high.Try again.");
                }
                else if (userentry < RandomNumber)
                {
                    Console.WriteLine($"You entered {userentry}. That's too low .Try again.");
                }
                else
                {
                    Console.WriteLine($"You entered {userentry}. That's right.Good job.");
                    
                }

                
            }
        }
    }
}

